### ISSUE TITLE
mobile-ffmpeg build fails at fontconfig

### ISSUE THREAD

**Issue by nofaceanime** [tanersener/mobile-ffmpeg#445]
**Description**
I already installed all prerequisites that were mention for android in wiki page. I then tried to build, but it fails at fontconfig. I did rebuild libuuid, but still fontconfig fails. I just cloned the repo so i am using the latest mobile-ffmpeg git clone. I am working on computer with ubuntu 20.04 lts version OS.

**Expected behavior**
fontconfig should build successfully after rebuilding libuuid

**Current behavior**
fontconfig fails to build even after rebuilding libuuid

**Screenshots**

**Logs**
```bash
make[3]: Leaving directory '/home/noface/Desktop/mobile-ffmpeg/src/fontconfig/src'
make[2]: Leaving directory '/home/noface/Desktop/mobile-ffmpeg/src/fontconfig/src'
Making all in fc-cache
make[2]: Entering directory '/home/noface/Desktop/mobile-ffmpeg/src/fontconfig/fc-cache'
  CC       fc-cache.o
  CCLD     fc-cache
/home/noface/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lfreetype
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeQueryFaceInternal: error: undefined reference to 'FT_Get_MM_Var'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeQueryFaceInternal: error: undefined reference to 'FT_Get_Sfnt_Table'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeQueryFaceInternal: error: undefined reference to 'FT_Get_Sfnt_Name_Count'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeQueryFaceInternal: error: undefined reference to 'FT_Get_Sfnt_Name'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeQueryFaceInternal: error: undefined reference to 'FT_Get_Sfnt_Name'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeQueryFaceInternal: error: undefined reference to 'FT_Get_Sfnt_Name'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeQueryFaceInternal: error: undefined reference to 'FT_Get_Postscript_Name'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeQueryFaceInternal: error: undefined reference to 'FT_Get_Sfnt_Table'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeQueryFaceInternal: error: undefined reference to 'FT_Load_Sfnt_Table'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function IA__FcFreeTypeQueryAll: error: undefined reference to 'FT_Init_FreeType'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function IA__FcFreeTypeQueryAll: error: undefined reference to 'FT_New_Face'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function IA__FcFreeTypeQueryAll: error: undefined reference to 'FT_Get_MM_Var'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function IA__FcFreeTypeQueryAll: error: undefined reference to 'FT_Set_Var_Design_Coordinates'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function IA__FcFreeTypeQueryAll: error: undefined reference to 'FT_Done_Face'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function IA__FcFreeTypeQueryAll: error: undefined reference to 'FT_New_Face'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function IA__FcFreeTypeQueryAll: error: undefined reference to 'FT_Set_Var_Design_Coordinates'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function IA__FcFreeTypeQueryAll: error: undefined reference to 'FT_Done_Face'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function IA__FcFreeTypeQueryAll: error: undefined reference to 'FT_Done_FreeType'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function IA__FcFreeTypeCharSet: error: undefined reference to 'FT_Select_Charmap'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function IA__FcFreeTypeCharSet: error: undefined reference to 'FT_Get_First_Char'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function IA__FcFreeTypeCharSet: error: undefined reference to 'FT_Load_Glyph'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function IA__FcFreeTypeCharSet: error: undefined reference to 'FT_Get_Next_Char'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeSpacing: error: undefined reference to 'FT_Get_Sfnt_Table'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeSpacing: error: undefined reference to 'FT_Select_Size'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeSpacing: error: undefined reference to 'FT_Select_Charmap'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeSpacing: error: undefined reference to 'FT_Get_First_Char'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeSpacing: error: undefined reference to 'FT_Get_Advance'
../src/.libs/libfontconfig.a(fcfreetype.o):fcfreetype.c:function FcFreeTypeSpacing: error: undefined reference to 'FT_Get_Next_Char'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Makefile:515: fc-cache] Error 1
make[2]: Leaving directory '/home/noface/Desktop/mobile-ffmpeg/src/fontconfig/fc-cache'
make[1]: *** [Makefile:600: all-recursive] Error 1
make[1]: Leaving directory '/home/noface/Desktop/mobile-ffmpeg/src/fontconfig'
make: *** [Makefile:484: all] Error 2
```

**Environment**
 - Platform: [Android]
 - Architecture: [arm-v7a, arm-v7a-neon, arm64-v8a, x86, x86_64]
 - Android Studio version [4.0]
 - Android NDK version [21.0.6113669]

**Comment by tanersener** [comment]
`/home/noface/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lfreetype`

There is an error about `freetype`. Did you try to rebuild it too?

**Comment by nofaceanime** [comment]
somehow i tried exact same thing on my other computer with ubuntu 18 and it worked successfully without any issue. I guess, new ubuntu 20.04 has some issues. still doesn't work on latest ubuntu 20.04 but works just fine in ubuntu 18, for now issue is resolved.
